/**
 * Development utility: clears generated alerts and their dedup state.
 *
 *   npm run alerts:reset
 *
 * Alert documents embed their message text at the moment they fire, so when
 * the wording or threshold logic changes, previously generated alerts keep the
 * old copy. During development that means stale (and possibly wrong) text stays
 * on the dashboard until it is cleared and regenerated by the next poll.
 *
 * Clearing alertState as well is important: without it the dedup machine still
 * believes each signal is active, so nothing would re-fire and the dashboard
 * would simply go empty.
 *
 * This is safe to run in development. Do NOT run it against a deployment whose
 * alert history is being used as evaluation evidence — that history is a
 * thesis artifact and cannot be reconstructed.
 */
import { db, COLLECTIONS } from '../src/lib/firebase/admin';

async function clearCollection(name: string): Promise<number> {
  const snap = await db().collection(name).get();
  if (snap.empty) return 0;

  const batch = db().batch();
  snap.docs.forEach((doc) => batch.delete(doc.ref));
  await batch.commit();
  return snap.size;
}

async function main() {
  if (process.env.NODE_ENV === 'production' && !process.argv.includes('--force')) {
    throw new Error('Refusing to clear alert history in production without --force');
  }

  // emailJobs too. Clearing alerts while leaving their queued jobs behind left
  // every one of them pointing at a document that no longer exists, and the
  // dispatcher could only report "alert missing" — which reads as a broken
  // mailer rather than as debris from a reset.
  for (const name of [COLLECTIONS.alerts, COLLECTIONS.alertState, COLLECTIONS.emailJobs]) {
    const count = await clearCollection(name);
    console.log(`cleared ${count} document(s) from ${name}`);
  }
  console.log('\nRun the poll-dams cron to regenerate alerts from current conditions.');
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(`FAILED: ${err.message}`);
    process.exit(1);
  });
